In [1]:
import numpy as np

In [2]:
arr_1d=np.array([1,2,3])
arr_1d

array([1, 2, 3])

In [3]:
arr_0d=np.array(0)
arr_0d

array(0)

In [4]:
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr_3d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr_3d.ndim

2

In [7]:
arr_2d.ndim

2

In [8]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
ones=np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

In [10]:
random_arr=np.random.random((3,3))
random_arr

array([[0.40465123, 0.35467693, 0.35740354],
       [0.38025946, 0.14483407, 0.16464074],
       [0.51063447, 0.58993607, 0.59239854]])

In [11]:
identity=np.eye(2)
identity

array([[1., 0.],
       [0., 1.]])

In [12]:
arr_arange=np.arange(0,10,2)
arr_arange

array([0, 2, 4, 6, 8])

In [13]:
print("shape :",arr_2d.shape)
print("dimension :",arr_2d.ndim)
print("size :",arr_2d.size)
print("dimention type :",arr_2d.dtype)



shape : (2, 3)
dimension : 2
size : 6
dimention type : int64


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.
Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

In [14]:
temp_data=np.array([[22,25,20],[24,26,23]])
temp_data

array([[22, 25, 20],
       [24, 26, 23]])

In [15]:
print("shape :",temp_data.shape)
print("dimension :",temp_data.ndim)
print("size :",temp_data.size)
print("dimention type :",temp_data.dtype)

shape : (2, 3)
dimension : 2
size : 6
dimention type : int64


In [16]:
new_gh=np.array([[21,23,22]])

In [17]:
updated_temp_data=np.append(temp_data,new_gh,axis=0)
updated_temp_data

array([[22, 25, 20],
       [24, 26, 23],
       [21, 23, 22]])

In [18]:
sensor_error_flags=np.zeros((2,3))

In [19]:
greenhouse_identity=np.eye(3)

In [20]:
print("senors sent temp data : \nGH1 : ",updated_temp_data[0],"\nGH2 : ",updated_temp_data[1],"\nGH3 : ",updated_temp_data[2])
print("sensor error flag :\n",sensor_error_flags)
print("green house identity :\n",greenhouse_identity)

senors sent temp data : 
GH1 :  [22 25 20] 
GH2 :  [24 26 23] 
GH3 :  [21 23 22]
sensor error flag :
 [[0. 0. 0.]
 [0. 0. 0.]]
green house identity :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
updated_temp_data[:,1:]

array([[25, 20],
       [26, 23],
       [23, 22]])

Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [22]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])

In [23]:
print("No of apple boxes shipped on Wednesday :",shipments[0][2])

No of apple boxes shipped on Wednesday : 55


In [24]:
print("no of apple boxes shipped in weekdays(mon-fri) are : ",shipments[0,:5])
print("no of Oranges boxes shipped in weekdays(mon-fri) are : ",shipments[1,:5])

no of apple boxes shipped in weekdays(mon-fri) are :  [50 60 55 70 65]
no of Oranges boxes shipped in weekdays(mon-fri) are :  [40 45 50 60 55]


In [25]:
print("no of apple boxes shipped in weekends(sat&sun) are : ",shipments[0,5:])
print("no of Oranges boxes shipped in weekends(sat&sun) are : ",shipments[1,5:])

no of apple boxes shipped in weekends(sat&sun) are :  [80 90]
no of Oranges boxes shipped in weekends(sat&sun) are :  [70 75]


In [26]:
print("No of apple boxes shipped from Wednesday to Saturday :",shipments[0][2:6])

No of apple boxes shipped from Wednesday to Saturday : [55 70 65 80]


In [27]:
shipments[0,5]=100
print("shipments of updated apples : ",shipments[0])

shipments of updated apples :  [ 50  60  55  70  65 100  90]


1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)

In [28]:
x=np.array([1,2,3])
y=np.array([4,5,6])
sum=np.add(x,y)
sub=np.subtract(x,y)
mul=np.multiply(x,y)
div=np.divide(x,y)
p=np.power(x,y)

In [29]:
print(x,y,sum,sub,mul,div,p,sep="\n")

[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [30]:
print(np.max(x))

3


You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [31]:
farm1=np.array([[10,11,12],[9,11,10],[12,13,14],[8,7,9]])
farm2=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farm3=np.array([[15,16,14],[14,13,15],[16,17,19],[12,11,13]])
production_all=np.array([farm1,farm2,farm3])
print(production_all)

[[[10 11 12]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 19]
  [12 11 13]]]


In [32]:
print("shape :",production_all.shape)
print("dimension :",production_all.ndim)
print("size :",production_all.size)
print("dimention type :",production_all.dtype)

shape : (3, 4, 3)
dimension : 3
size : 36
dimention type : int64


In [33]:
per_farm=np.add(farm1,farm2,farm3)
total_per_farm=production_all.sum(axis=(1,2))
print(total_per_farm)
print(production_all.mean(axis=(1,2)))
print(production_all.sum(axis=(0)))

[126 234 175]
[10.5        19.5        14.58333333]
[[45 46 47]
 [41 44 44]
 [50 53 54]
 [37 36 38]]


In [34]:
t=production_all.sum(axis=(1,2))
t

array([126, 234, 175])

In [35]:
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]]
[1 2 3 4]


In [36]:
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,5))

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [37]:
print(arr[arr>3])
ind=[2,1]
print(arr[ind])

[4 5 6]
[3 2]


In [38]:
#copy or view
#view shares memory
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)
#copy does not shares memory
copy=arr.copy()
copy[0]=10
print(arr)

[10  2  3]
[10  2  3]


In [39]:
#saving and loading
arr=np.array([1,2,3])
np.save('array.npy',arr)
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [40]:
arr1D=np.arange(10,51)
print(arr1D)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [41]:
arr2D=np.random.random((3,3))
print(arr2D)

[[0.95218104 0.52300749 0.08712889]
 [0.57361502 0.37274154 0.80481393]
 [0.35644441 0.98570947 0.01855718]]


In [42]:
print("for arr1D\nshape :",arr1D.shape)
print("dimension :",arr1D.ndim)
print("size :",arr1D.size)
print("dimention type :",arr1D.dtype,end='\n\n')

print("for arr3D\nshape :",arr2D.shape)
print("dimension :",arr2D.ndim)
print("size :",arr2D.size)
print("dimention type :",arr2D.dtype)

for arr1D
shape : (41,)
dimension : 1
size : 41
dimention type : int64

for arr3D
shape : (3, 3)
dimension : 2
size : 9
dimention type : float64


In [43]:
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
iden=np.eye(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
arr1D=np.add(arr1D,5)
print(arr1D)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [52]:
ones = np.ones((3, 3))
zeros = np.zeros((3, 3))
iden = np.eye(3)

# Multiplications
arr_mul2D = np.multiply(arr2D, ones)
print("Multiplication with ones:\n", arr_mul2D)

arr_mul2D = np.multiply(arr2D, zeros)
print("\nMultiplication with zeros:\n", arr_mul2D)

arr_mul2D = np.multiply(arr2D, iden)
print("\nMultiplication with identity matrix:\n", arr_mul2D)


Multiplication with ones:
 [[0.95218104 0.52300749 0.08712889]
 [0.57361502 0.37274154 0.80481393]
 [0.35644441 0.98570947 0.01855718]]

Multiplication with zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Multiplication with identity matrix:
 [[0.95218104 0.         0.        ]
 [0.         0.37274154 0.        ]
 [0.         0.         0.01855718]]


In [53]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [48]:
arrI_S = np.arange(1, 26).reshape(5, 5)
print(arrI_S)
print(arrI_S[0])
print(arrI_S[:,len(arrI_S)-1])
print(arrI_S[:3,:2])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]


In [47]:
import random
arr4=[random.randint(10,100) for _ in range(10)]
print(arr4)
print(np.max(arr4))
print(np.min(arr4))
print(np.mean(arr4))
print(np.std(arr4))

[33, 94, 23, 58, 76, 81, 34, 81, 92, 98]
98
23
67.0
26.551836094703507


In [49]:
arr6=np.arange(1,13)
print(arr6)
arr6=arr6.reshape(3,4)
print(arr6)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
ones=np.ones((3,3))
arr7=np.add(ones,[1,2,3])
print(arr7)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [51]:
arr8=np.array([random.randint(1,51) for _ in range(25)])
print(arr8[arr8%5==0])

[20 30 35  5]
